apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar
  labels:
    app: acnhapi
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: acnhapi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    tier: backend
  template:
    metadata:
      labels:
        app: acnhapi
        tier: backend
    spec:
      volumes:
        - name: certificates
          secret:
            secretName: acnhapi-certificates
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
      containers:
        - name: acnhapi-nginxsidecar
          image: nginx:1.19
          command: ["/home/reload-nginx.sh"]
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: certificates
            - mountPath: /etc/nginx/conf.d
              name: configmap-volume
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]