apiVersion: apps/v1
kind: Deployment
metadata:
  name: acnhcompanion-api-stable
  namespace: acnhcompanion-api
  labels:
    app.kubernetes.io/name: acnhcompanion-api-stable
    app.kubernetes.io/instance: acnhcompanion-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: acnhcompanion-api-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acnhcompanion-api-stable
        app.kubernetes.io/instance: acnhcompanion-api
    spec:
      containers:
        - name: acnhcompanion-api
          image: samanthaemilyrachelb/acnhcompanion-api:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: acnhcompanion-api-stable-db-config
                  key: host
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: acnhcompanion-api-stable-db-secret
                  key: database
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: acnhcompanion-api-stable-db-secret
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acnhcompanion-api-stable-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: acnhcompanion-api-stable
  namespace: acnhcompanion-api
  labels:
    app.kubernetes.io/name: acnhcompanion-api-stable
    app.kubernetes.io/instance: acnhcompanion-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: achncompanion-api-stable-ingress
  namespace: acnhcompanion-api
  labels:
    app.kubernetes.io/name: acnhcompanion-api-stable-ingress
    app.kubernetes.io/instance: acnhcompanion-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.acnhcompanion.io
      http:
        paths:
          - path: /
            backend:
              serviceName: acnhcompanion-api-stable-ingress
              servicePort: 3000

