apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-ingress-nginx-controller
  namespace: ingress-nginx
data:
  compute-full-forwarded-for: 'true'
  #ssl-ciphers: 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
  ssl-protocols: 'TLSv1.3'
  ssl-redirect: 'true'
  #ssl-ecdh-curve: 'X25519:prime256v1:secp384r1'
  #ssl-ecdh-curve: "secp384r1"
  ssl-dh-param: "ingress-nginx/dhparam"
  use-forwarded-headers: 'true'
  use-http2: 'true'
  use-proxy-protocol: 'true'
  http-snippet: |
    # SSL
    ssl_session_cache shared:SSL:10m;

    server {
      listen 18080;
      location /nginx_status {
        allow all;
        stub_status on;
      }
    }
  nginx-config: |-
    ad_identifiers:
      - nginx
    init_config:
    instances:
      - name: "nginx_status_url"
        url: "http://%%host%%:18080/nginx_status"
        timeout: 1
      - name: "prometheus_url"
        url: "http://%%host%%:10254/metrics"
        timeout: 1
